# API Gateway Configuration Example
# Copy this file to gateway.yaml and update with your actual values

server:
  name: sydney-health-gateway
  port: 8080
  environment: development
  read_timeout: 30s
  write_timeout: 30s
  graceful_shutdown_timeout: 30s
  log_level: debug

database:
  host: ${DB_HOST:-localhost}
  port: ${DB_PORT:-5432}
  name: ${DB_NAME:-sydney_health}
  username: ${DB_USER:-your_db_user}
  password: ${DB_PASSWORD:-your_secure_password}
  ssl_mode: ${DB_SSL_MODE:-disable}
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m

redis:
  host: ${REDIS_HOST:-localhost}
  port: ${REDIS_PORT:-6379}
  password: ${REDIS_PASSWORD}
  db: ${REDIS_DB:-0}
  pool_size: 10
  min_idle_conns: 5
  max_retry: 3

auth:
  jwt_secret: ${JWT_SECRET:-your_jwt_secret_here}
  token_expiry: ${JWT_EXPIRY:-24h}
  refresh_token_expiry: ${JWT_REFRESH_EXPIRY:-168h}
  skip_paths:
    - /health
    - /metrics
    - /api/v1/auth/login
    - /api/v1/auth/register
    - /api/v1/auth/refresh

services:
  member:
    host: ${MEMBER_SERVICE_HOST:-localhost}
    port: ${MEMBER_SERVICE_PORT:-50051}
    timeout: 10s
  benefits:
    host: ${BENEFITS_SERVICE_HOST:-localhost}
    port: ${BENEFITS_SERVICE_PORT:-50052}
    timeout: 10s
  claims:
    host: ${CLAIMS_SERVICE_HOST:-localhost}
    port: ${CLAIMS_SERVICE_PORT:-50053}
    timeout: 10s
  provider:
    host: ${PROVIDER_SERVICE_HOST:-localhost}
    port: ${PROVIDER_SERVICE_PORT:-50054}
    timeout: 10s
  messaging:
    host: ${MESSAGING_SERVICE_HOST:-localhost}
    port: ${MESSAGING_SERVICE_PORT:-50055}
    timeout: 10s

kafka:
  brokers:
    - ${KAFKA_BROKER_1:-localhost:9092}
  consumer_group: ${KAFKA_CONSUMER_GROUP:-sydney-health-gateway}
  topics:
    claims: claims
    messages: messages
    audit: audit
    member_updates: member-updates
    benefit_changes: benefit-changes

cors:
  allowed_origins:
    - http://localhost:3000
    - https://localhost:3000
    # Add your production domains here
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Authorization
    - Content-Type
    - X-Request-ID
  exposed_headers:
    - X-Total-Count
    - X-Page-Number
  allow_credentials: true
  max_age: 300

rate_limiting:
  enabled: true
  requests_per_minute: ${RATE_LIMIT_RPM:-100}
  burst: ${RATE_LIMIT_BURST:-20}
  exclude_paths:
    - /health
    - /metrics

metrics:
  enabled: ${METRICS_ENABLED:-true}
  port: ${METRICS_PORT:-9090}
  path: /metrics
  namespace: sydney_health
  subsystem: gateway

tracing:
  enabled: ${TRACING_ENABLED:-true}
  service_name: sydney-health-gateway
  jaeger_endpoint: ${JAEGER_ENDPOINT:-http://localhost:14268/api/traces}
  sampling_rate: ${TRACING_SAMPLING_RATE:-0.1}

security:
  encryption_key: ${ENCRYPTION_KEY}
  api_key_header: ${API_KEY_HEADER:-X-API-Key}
  enable_request_logging: true
  mask_sensitive_data: true
  
cache:
  default_ttl: 5m
  max_entries: 10000
  
circuit_breaker:
  max_requests: 100
  interval: 10s
  timeout: 30s
  failure_threshold: 0.5