groups:
  - name: sydney-health-alerts
    interval: 30s
    rules:
      # Service availability alerts
      - alert: ServiceDown
        expr: up{job=~"backend-services|web-app"} == 0
        for: 2m
        labels:
          severity: critical
          team: platform
        annotations:
          summary: "Service {{ $labels.instance }} is down"
          description: "{{ $labels.job }} service {{ $labels.instance }} has been down for more than 2 minutes."

      # High error rate
      - alert: HighErrorRate
        expr: |
          (
            sum(rate(http_requests_total{status=~"5.."}[5m])) by (service)
            /
            sum(rate(http_requests_total[5m])) by (service)
          ) > 0.05
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High error rate in {{ $labels.service }}"
          description: "Error rate is above 5% for {{ $labels.service }} (current: {{ $value | humanizePercentage }})"

      # High latency
      - alert: HighLatency
        expr: |
          histogram_quantile(0.95,
            sum(rate(http_request_duration_seconds_bucket[5m])) by (service, le)
          ) > 0.5
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High latency in {{ $labels.service }}"
          description: "95th percentile latency is above 500ms for {{ $labels.service }} (current: {{ $value }}s)"

      # Database connection issues
      - alert: DatabaseConnectionFailure
        expr: mysql_up == 0 or postgres_up == 0
        for: 1m
        labels:
          severity: critical
          team: database
        annotations:
          summary: "Database connection failure"
          description: "Unable to connect to database {{ $labels.instance }}"

      # Kafka lag
      - alert: KafkaConsumerLag
        expr: kafka_consumer_lag > 10000
        for: 5m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "Kafka consumer lag is high"
          description: "Consumer {{ $labels.consumer_group }} has lag of {{ $value }} messages on topic {{ $labels.topic }}"

      # Memory usage
      - alert: HighMemoryUsage
        expr: |
          (
            container_memory_usage_bytes{pod!=""}
            / 
            container_spec_memory_limit_bytes{pod!=""}
          ) > 0.9
        for: 5m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "High memory usage in {{ $labels.pod }}"
          description: "Pod {{ $labels.pod }} memory usage is above 90% (current: {{ $value | humanizePercentage }})"

      # CPU usage
      - alert: HighCPUUsage
        expr: |
          rate(container_cpu_usage_seconds_total{pod!=""}[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "High CPU usage in {{ $labels.pod }}"
          description: "Pod {{ $labels.pod }} CPU usage is above 80% (current: {{ $value | humanizePercentage }})"

      # Disk space
      - alert: DiskSpaceLow
        expr: |
          (
            node_filesystem_avail_bytes{mountpoint="/"}
            /
            node_filesystem_size_bytes{mountpoint="/"}
          ) < 0.1
        for: 5m
        labels:
          severity: critical
          team: platform
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Disk space is below 10% on {{ $labels.instance }} (current: {{ $value | humanizePercentage }} free)"

      # Certificate expiry
      - alert: CertificateExpiringSoon
        expr: certmanager_certificate_expiration_timestamp_seconds - time() < 7 * 24 * 60 * 60
        for: 1h
        labels:
          severity: warning
          team: security
        annotations:
          summary: "Certificate expiring soon"
          description: "Certificate {{ $labels.name }} in namespace {{ $labels.namespace }} will expire in less than 7 days"

      # Claims processing delays
      - alert: ClaimsProcessingDelay
        expr: |
          histogram_quantile(0.95,
            sum(rate(claims_processing_duration_seconds_bucket[5m])) by (le)
          ) > 300
        for: 10m
        labels:
          severity: warning
          team: claims
        annotations:
          summary: "Claims processing is slow"
          description: "95th percentile of claims processing time is above 5 minutes (current: {{ $value }}s)"

      # Member authentication failures
      - alert: HighAuthenticationFailureRate
        expr: |
          sum(rate(auth_failures_total[5m])) > 10
        for: 5m
        labels:
          severity: warning
          team: security
        annotations:
          summary: "High authentication failure rate"
          description: "Authentication failure rate is {{ $value }} per second"