platform :ios, '13.0'
use_frameworks!

target 'SydneyHealth' do
  # RIBs Architecture
  pod 'RIBs', '~> 0.9'
  
  # Networking
  pod 'Alamofire', '~> 5.8'
  pod 'SwiftGRPC', '~> 0.13'
  
  # UI
  pod 'SnapKit', '~> 5.6'
  pod 'Kingfisher', '~> 7.9'
  pod 'Lottie', '~> 4.3'
  
  # Reactive
  pod 'RxSwift', '~> 6.6'
  pod 'RxCocoa', '~> 6.6'
  
  # Utilities
  pod 'SwiftLint', '~> 0.53'
  pod 'IQKeyboardManagerSwift', '~> 6.5'
  pod 'SwiftKeychainWrapper', '~> 4.0'
  
  # Analytics & Monitoring
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Performance'
  
  target 'SydneyHealthTests' do
    inherit! :search_paths
    pod 'Quick', '~> 7.0'
    pod 'Nimble', '~> 13.0'
    pod 'RxTest', '~> 6.6'
    pod 'RxBlocking', '~> 6.6'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end